= Vert.X Maven Plugin


image:https://circleci.com/gh/kameshsampath/vertx-maven-plugin.svg?style=shield["CircleCI", link="https://circleci.com/gh/kameshsampath/vertx-maven-plugin"]

This Maven plugin is a one-stop-shop for packaging, running, starting and stoppping  http://vertx.io[Vert.X] Java applications.  This plugin
combines the goals of Maven Shade, Maven Exec into one, allowing the users to have a simplified pom.xml.

WARNING: Most of the features are under development and tend to break. If you see it breaking,
please open an https://github.com/kameshsampath/vertx-maven-plugin/issues[issue]

== Features

The following are the list of features that will be part of the plugin:

- [*] Packaging the Vertx Application as fat or uber jar
- [*] Running vertx application as part of maven build in forked or unforked mode
- [ ] Ability to pass vertx configuration *-conf* automatically if a file named artifactId.json or artifactId.yaml
is present in project sources under _src/main/conf_.  The users can also configure the same via plugin configuration.
Refer to https://kameshsampath.github.io/vertx-maven-plugin/#vertx:run[vertx:run] for more information
- [ ] Ability to perform when redeploy is enabled, please check the
https://kameshsampath.github.io/vertx-maven-plugin/#vertx:run[vertx:run] for more information

=== Plugin Goals
[cols="1,3"]
|===
|Goal | Description
| https://kameshsampath.github.io/vertx-maven-plugin/#vertx:package[vertx-maven-plugin:package]
| Package  http://vertx.io[Vert.X] application into a fat jar
| https://kameshsampath.github.io/vertx-maven-plugin/#vertx:run[vertx-maven-plugin:run]
| Runs the  http://vertx.io[Vert.X] application from the maven build
| vertx-maven-plugin:start
| Will start the http://vertx.io[Vert.X] application as daemon (WIP)
| vertx-maven-plugin:stop
| Will stop the  http://vertx.io[Vert.X] application running as daemon (WIP)
|===

== Documentation

* https://kameshsampath.github.io/vertx-maven-plugin/[Plugin Documentation]

== Issues

If you feel to add any feature you can open issue in https://github.com/kameshsampath/vertx-maven-plugin/issues and
we will try to address it as soon as possible

== Contributing

Thanks to Ronald Huß for his contribution and support. If you wish to contribute a patch or feature, please open
a issue in https://github.com/kameshsampath/vertx-maven-plugin/issues and send in a PR.
